# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master

pr:
  autoCancel: true
  drafts: false
  branches:
    include:
    - master

name: Test_System_Build.$(Rev:.r)

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo echo 'Reason: $(Build.Reason)'
    echo echo 'SourceVersion: $(Build.SourceVersion)'
    echo echo 'QueuedBy: $(Build.QueuedBy)'
    echo echo 'RequestedFor: $(Build.RequestedFor)'
  displayName: 'Additional information'

- script: echo '$(Build.BuildNumber)'
  displayName: 'Build Number'
  
- script: echo "##vso[task.setvariable variable=BuildNum; isoutput=true]$(Build.BuildNumber)"
