resources:
  pipelines:
  - pipeline: buildNumber
    source: TestBuildNumber
    trigger:
      branches:
      - master

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: 'env | sort'
  displayName: "echo Environment Variables"
- task: DownloadBuildArtifacts@0
  displayName: 'Download variables'
  inputs:
    buildType: 'specific'
    project: 'Emmons'
    pipeline: '106'
    buildVersionToDownload: 'latest'
    downloadType: 'specific'
    downloadPath: '$(System.ArtifactsDirectory)'

- script: cat $(System.ArtifactsDirectory)/variables/test_pipeline.env
  displayName: 'Restore Enviornment Variables'
- script: echo "BuildNum:$(BuildNum)"
  displayName: 'echo envrionemtn variables'
