# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master

pr:
  autoCancel: true
  drafts: false
  branches:
    include:
    - master

name: Test.System.Build$(Rev:.r)

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "##vso[task.setvariable variable=BuildNum; isoutput=true]$(Build.BuildNumber)"
