name: dotnet
author: 'Blair Murri'
description: 'Runs dotnet'
inputs:
  command:
    description: 'Command to run'
    required: true
  directory:
    description: 'path where command is run'
    required: false
    default: ${{ github.workspace }}
  restore:
    description: 'Performs restore if needed (set to false to suppress)'
    required: false
    default: true
  build:
    description: 'Performs build if needed (set to false to suppress)'
    required: false
    default: true
  additional:
    description: 'Any additional arguments'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - env:
        RESTORE: ${{ fromJSON('["--no-restore", ""]')[ false != inputs.restore ] }}
        BUILD: ${{ fromJSON('["--no-build", ""]')[ false != inputs.build ] }}
      run: dotnet ${{ inputs.command }} ${{ format('{0} {1}', env.restore, env.build) }} ${{ inputs.additional }}
      shell: bash
      working-directory: ${{ inputs.directory }}
