name: dotnet
author: 'Blair Murri'
description: 'Runs dotnet'
inputs:
  command:
    description: 'Command to run'
    required: true
    type: string
  directory:
    description: 'path where command is run'
    required: false
    type: string
    default: ''
  restore:
    description: 'Performs restore if needed (set to false to suppress)'
    type: boolean
    required: false
    default: true
  build:
    description: 'Performs build if needed (set to false to suppress)'
    type: boolean
    required: false
    default: true
  additional:
    description: 'Any additional arguments'
    required: false
    type: string
    default: ''

runs:
  using: "composite"
  steps:
    - name: command
      env:
        RESTORE: ${{ fromJSON('["--no-restore", ""]')[ inputs.restore ] }}
        BUILD: ${{ fromJSON('["--no-build", ""]')[ inputs.build ] }}
        workDir: ${{ fromJSON('[inputs.directory, github.workspace]')[ '' == inputs.directory ] }}
      run: dotnet ${{ inputs.command }} ${{ format('{0} {1}', env.restore, env.build) }} ${{ inputs.additional }}
      shell: bash
      working-directory: ${{ env.workDir }}
