name: dotnet
author: 'Blair Murri'
description: 'Runs dotnet'
inputs:
  command:
    description: 'Command to run'
    required: true
    type: string
  directory:
    description: 'path where command is run'
    required: false
    type: string
    default: ''
  restore:
    description: 'Performs restore if needed (set to false to suppress)'
    type: boolean
    required: false
    default: true
  build:
    description: 'Performs build if needed (set to false to suppress)'
    type: boolean
    required: false
    default: true
  additional:
    description: 'Any additional arguments'
    required: false
    type: string
    default: ''

# inputs.<name> => $INPUT_<name>
runs:
  using: "composite"
  steps:
    - name: pushd
      run: pushd ${{ inputs.directory }}
        shell: bash
      if: ${{ '' != inputs.directory }}
    - name: command
      env.restore: ${{ fromJSON('["--no-restore", ""]')[ inputs.restore ] }}
      env.build: ${{ fromJSON('["--no-build", ""]')[ inputs.build ] }}
      run: dotnet ${{ inputs.command }} ${{ format('{0} {1}', env.restore, env.build) }} ${{ inputs.additional }}
        shell: bash
    - name: popd
      run: popd
        shell: bash
      if: ${{ '' != inputs.directory }}
