name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-x64, win-x64, osx-x64]
        projects: [TesApi.Web, TriggerService]
    env:
       EnableCompressionInSingleFile: "true"
       PublishSingleFile: "true"
       SelfContained: "true"
       PublishReadyToRun: "true"
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore -r ${{ matrix.platform }}
    - name: Build
      run: dotnet build --no-restore -r linux-x64
      working-directory:
        src/Common
        src/Common.Tests
        src/CromwellApiClient
        src/deploy-cromwell-on-azure
        src/deploy-cromwell-on-azure.Tests
        src/Tes
        src/TesApi.Web
        src/TesApi.Tests
        src/TriggerService
        src/TriggerService.Tests
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-build --verbosity normal -r linux-x64
      working-directory: src/${{ matrix.projects }}
    - name: Publish
      run: dotnet publish --no-build --verbosity normal --self-contained true -r ${{ matrix.platform }}
      working-directory: src/deploy-cromwell-on-azure
