name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-x64, win-x64, osx-x64]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      uses: ./.github/actions/dotnet/
      with:
        command: restore
        restore: true
        build: true
        additional: "-r ${{ matrix.platform }}"
    - name: Build Deploy Tool
      env:
        EnableCompressionInSingleFile: "true"
        PublishSingleFile: "true"
        SelfContained: "true"
        UseAppHost: "true"
      uses: ./.github/actions/dotnet/
      with:
        command: build
        directory: "src/deploy-cromwell-on-azure"
        restore: false
        build: true
        additional: "-r ${{ matrix.platform }}"
    - name: Build Tes
      uses: ./.github/actions/dotnet/
      with:
        command: build
        directory: "src/TesApi.Web"
        restore: false
        build: true
        additional: "-r ${{ matrix.platform }}"
      if: ${{ 'linux-x64' == matrix.platform }}
    - name: Build TriggerService
      uses: ./.github/actions/dotnet/
      with:
        command: build
        directory: "src/TriggerService"
        restore: false
        build: true
        additional: "-r ${{ matrix.platform }}"
      if: ${{ 'linux-x64' == matrix.platform }}
    - name: Build Common Tests
      uses: ./.github/actions/dotnet/
      with:
        command: build
        directory: "src/Common.Tests"
        restore: false
        build: true
    - name: Build Deployer Tests
      uses: ./.github/actions/dotnet/
      with:
        command: build
        directory: "src/deploy-cromwell-on-azure.Tests"
        restore: false
        build: true
    - name: Build Tes Tests
      uses: ./.github/actions/dotnet/
      with:
        command: build
        directory: "src/TesApi.Tests"
        restore: false
        build: true
      if: ${{ 'linux-x64' == matrix.platform }}
    - name: Build TriggerService Tests
      uses: ./.github/actions/dotnet/
      with:
        command: build
        directory: "src/TriggerService.Tests"
        restore: false
        build: true
      if: ${{ 'linux-x64' == matrix.platform }}
    - name: Run Common Tests
      uses: ./.github/actions/dotnet/
      with:
        command: test
        directory: "src/Common.Tests"
        restore: true
        build: false
        additional: "--verbosity normal"
    - name: Run Deployer Tests
      uses: ./.github/actions/dotnet/
      with:
        command: test
        directory: "src/deploy-cromwell-on-azure.Tests"
        restore: true
        build: false
        additional: "--verbosity normal"
    - name: Run Tes Tests
      uses: ./.github/actions/dotnet/
      with:
        command: test
        directory: "src/TesApi.Tests"
        restore: true
        build: false
        additional: "--verbosity normal"
      if: ${{ 'linux-x64' == matrix.platform }}
    - name: Run TriggerService Tests
      uses: ./.github/actions/dotnet/
      with:
        command: test
        directory: "src/TriggerService.Tests"
        restore: true
        build: false
        additional: "--verbosity normal"
      if: ${{ 'linux-x64' == matrix.platform }}
    - name: Publish Tes
      uses: ./.github/actions/dotnet/
      with:
        command: publish
        directory: "src/TesApi.Web"
        restore: true
        build: false
        additional: "--verbosity normal -r ${{ matrix.platform }}"
      if: ${{ 'linux-x64' == matrix.platform }}
    - name: Publish TriggerService
      uses: ./.github/actions/dotnet/
      with:
        command: publish
        directory: "src/TriggerService"
        restore: true
        build: false
        additional: "--verbosity normal -r ${{ matrix.platform }}"
      if: ${{ 'linux-x64' == matrix.platform }}
    - name: Publish Deploy Tool
      env:
        EnableCompressionInSingleFile: "true"
        PublishSingleFile: "true"
        SelfContained: "true"
        UseAppHost: "true"
      uses: ./.github/actions/dotnet/
      with:
        command: publish
        directory: "src/deploy-cromwell-on-azure"
        restore: true
        build: false
        additional: "--verbosity normal --self-contained true -r ${{ matrix.platform }}"
