name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-x64, win-x64, osx-x64]
        projects: [TesApi.Web, TriggerService]
    env:
       EnableCompressionInSingleFile: "true"
       PublishSingleFile: "true"
       SelfContained: "true"
       PublishReadyToRun: "true"
       UseAppHost: "true"
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      uses: /.github/actions/dotnet.yml@master
      with:
        command: restore
        restore: true
        build: true
        additional: "-r ${{ matrix.platform }}"
    - name: Build
      run: |
        pushd src/Common
        dotnet build --no-restore -r  ${{ matrix.platform }}
        popd
        pushd src/CromwellApiClient
        dotnet build --no-restore -r  ${{ matrix.platform }}
        popd
        pushd src/deploy-cromwell-on-azure
        dotnet build --no-restore -r  ${{ matrix.platform }}
        popd
        pushd src/Tes
        dotnet build --no-restore -r  ${{ matrix.platform }}
        popd
        pushd src/TesApi.Web
        dotnet build --no-restore -r  ${{ matrix.platform }}
        popd
        pushd src/TriggerService
        dotnet build --no-restore -r  ${{ matrix.platform }}
        popd
        export SelfContained=false
        export PublishSingleFile=false
        pushd src/Common.Tests
        dotnet build --no-restore
        popd
        pushd src/deploy-cromwell-on-azure.Tests
        dotnet build --no-restore
        popd
        pushd src/TesApi.Tests
        dotnet build --no-restore
        popd
        pushd src/TriggerService.Tests
        dotnet build --no-restore
        popd
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: |
        echo $SelfContained $PublishSingleFile
        dotnet publish --no-build --verbosity normal -r ${{ matrix.platform }}
      working-directory: src/${{ matrix.projects }}
    - name: Publish
      run: |
        echo $SelfContained $PublishSingleFile
        dotnet publish --no-build --verbosity normal --self-contained true -r ${{ matrix.platform }}
      working-directory: src/deploy-cromwell-on-azure
