name: TestAzure

on:
  check_run:
    types: completed

permissions:
  checks: read
  statuses: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      shell: bash
    - name: Dump GitHub context
      env:
        ENV_CONTEXT: ${{ toJson(env) }}
      run: echo "$ENV_CONTEXT"
      shell: bash
