name: TestAzure

on:
  check_run:
    types: completed
  check_suite:
    types: completed

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Do Test
      run: echo 'Test ran!'
      shell: bash
